---
title: "Sega Genesis Mini 2"
---

## Games

* After Burner II
* Alien Soldier
* Atomic Runner
* Bonanza Bros.
* ClayFighter
* Crusader of Centy
* Desert Strike: Return to the Gulf
* Earthworm Jim 2
* Elemental Master
* Fatal Fury 2
* Gain Ground
* Golden Axe II
* Granada
* Hellfire
* Herzog Zwei
* Lightening Force: Quest for the Darkstar
* Midnight Resistance
* OutRun
* OutRunners
* Phantasy Star II
* Populous
* RAINBOW ISLANDS -EXTRA-
* Ranger-X
* Ristar
* ROLLING THUNDER 2
* Shadow Dancer: The Secret of Shinobi
* Shining Force II
* Shining in the Darkness
* Sonic 3D Blast
* SPLATTERHOUSE 2
* Streets of Rage 3
* Super Hang-On
* SUPER STREET FIGHTER II THE NEW CHALLENGERS
* The Ooze
* The Revenge of Shinobi
* ToeJam & Earl in Panic on Funkotron
* Truxton
* VectorMan 2
* Viewpoint
* Virtua Racing
* Warsong
* Ecco the Dolphin (Sega CD)
* Ecco: The Tides of Time (Sega CD)
* Final Fight CD (Sega CD)
* Mansion of Hidden Souls (Sega CD)
* NIGHT STRIKER (Sega CD)
* Night Trap (Sega CD)
* Robo Aleste (Sega CD)
* Sewer Shark (Sega CD)
* Shining Force CD (Sega CD)
* SILPHEED (Sega CD)
* Sonic CD (Sega CD)
* THE NINJA WARRIORS (Sega CD)
* Devi & Pii (Special Content)
* Fantasy Zone (Special Content)
* Space Harrier II + Space Harrier (Special Content)
* Spatter (Special Content)
* Star Mobile (Special Content)
* Super Locomotive (Special Content)
* VS Puyo Puyo Sun (Special Content)