---
title: "Sega Genesis Mini 1"
---

## Games

* Alex Kidd in the Enchanted Castle (region exclusive)
* Altered Beast (region exclusive)
* Dr. Robotnik's Mean Bean Machine (region exclusive, sort of - it's essentially a reskinned Puyo Puyo)
* Earthworm Jim (region exclusive)
* Ecco the Dolphin (region exclusive)
* Eternal Champions (region exclusive)
* Kid Chameleon (region exclusive)
* Light Crusader (region exclusive)
* Shinobi III: Return of the Ninja Master (region exclusive)
* Sonic the Hedgehog Spinball (region exclusive)
* ToeJam & Earl (region exclusive)
* Vectorman (region exclusive)
* Virtua Fighter 2 (region exclusive)
* Alisia Dragoon
* Beyond Oasis (The Story of Thor: A Successor of the Light)
* Castle of Illusion Starring Mickey Mouse
* Castlevania: Bloodlines
* Comix Zone
* Columns
* Contra: Hard Corps
* Darius - brand new port!
* Dynamite Headdy
* Ghouls 'n Ghosts
* Golden Axe
* Gunstar Heroes
* Landstalker
* Mega Man: The Wily Wars
* Monster World IV
* Phantasy Star IV: The End of the Millennium
* Road Rash II
* Shining Force
* Sonic the Hedgehog
* Sonic the Hedgehog 2
* Space Harrier II
* Street Fighter II': Special Champion Edition
* Streets of Rage 2
* Strider
* Super Fantasy Zone
* Tetris - ridiculously rare version!
* Thunder Force III
* Wonder Boy in Monster World
* World of Illusion Starring Mickey Mouse and Donald Duck
